const fs = require('fs');

const file = 'src/app/layout.tsx';
let content = fs.readFileSync(file, 'utf8');

content = content.replace(
  'title: "Create Next App",',
  'title: "ระบบเงินเดือน โรงพยาบาลสามโคก",'
);

content = content.replace(
  'description: "Generated by create next app",',
  'description: "ระบบจัดการเงินเดือน โรงพยาบาลสามโคก",'
);

fs.writeFileSync(file, content);
console.log('Fixed metadata');
