name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    - name: Install dependencies
      working-directory: ./payroll-api
      run: npm ci
    - name: Build API
      working-directory: ./payroll-api
      run: npm run build

  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    - name: Install dependencies
      working-directory: ./payroll-web
      run: npm ci
    - name: Build Web
      working-directory: ./payroll-web
      run: npm run build
